### PR TITLE
Bitbucket-server support

### PR DESCRIPTION
**Pull request by jlehtimaki**
First of all thanks for good project!

I added missing Bitbucket server support.

Let me know if you want to make any changes or you disagree on how it's implemented

### CODE REVIEW

**Comment by jimsheldon** [comment]
Thanks for the contribution @jlehtimaki! We will review asap

**Comment by jimsheldon** [comment]
The tests fail since `plugin/plugin_test.go` now needs to pass the provider when invoking `New`, can you make that change? I suppose you can pass `github` even though the tests currently are not provider specific.

**Comment by jlehtimaki** [comment]
@jimsheldon thanks for taking a look!
I added both providers to the test. Hope this is ok!

**Review by jimsheldon — APPROVED** [review]

**Comment by jimsheldon** [comment]
@jlehtimaki merged!

I'm going to add a note to the README that bitbucket-server support is available but we are considering it experimental at the moment. If you can contribute any unit tests for `GetBBFilesChanged` that would be helpful.

**Comment by jlehtimaki** [comment]
Will do! Thanks @jimsheldon !

**Comment by jimsheldon** [comment]
This is included in 0.2.0 https://github.com/meltwater/drone-convert-pathschanged/releases/tag/v0.2.0

Thanks again!

**Pull request merged**
